### ISSUE TITLE


### ISSUE THREAD

**Issue by 0x0000000000000000000000000** [abhinath84/STLport#1]


**Comment by abhinath84** [comment]
Hi chigco,

I'm also trying to build STLport in VS2015 and got same kind of error. This is mostly due C++11 changes in C++ standard. Microsoft (Visual Studio team) changed the location of the C++ standard header file (like: **ctype.h**) location from '**..\Program Files (x86)\Microsoft Visual Studio 14.0\VC**' to '**..\Program Files (x86)\Windows Kit**s' which also causing compilation error.
I'm working on it, I'll update you as soon as I made the changes and build successfully.

Thanks,
Abhishek
